"""add fish audio api key

Revision ID: add_fish_audio_api_key
Revises: 
Create Date: 2024-12-22 12:44:18.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_fish_audio_api_key'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fish_audio_api_key', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fish_audio_api_key')
    # ### end Alembic commands ###
